# Generated by Django 5.0.6 on 2024-09-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='bio',
        ),
    ]
